In [1]:
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [22]:
# mask_indices_path = "/home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/2024-05-13/09-34-13/Instance_Masks_test__Real_World__WMSC/DJI_0029 (3).JPG__mask_indices.npz"
# mask_indices_path = "/home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/2024-05-13/11-05-05/Instance_Masks_test__Real_World__WMSC/DJI_0014 (3).JPG__mask_indices.npz"
mask_indices_path = "/home/papjuli/code/ETH/3DV_project/CityMagic3D/outputs/2024-05-13/11-05-05/Instance_Masks_test__Real_World__WMSC/DJI_0341.JPG__mask_indices.npz"
mask_indices = np.load(mask_indices_path)

In [23]:
mask_indices_ls = [mask_indices[k] for k in mask_indices]

In [24]:
mask_indices_ls[1]

array([ 918545,  918566,  918567,  918572,  918576,  918577,  918578,
        918581,  918582,  918583,  918584,  918746,  918747,  918748,
        918749,  918750,  918751,  918752,  918755,  918758,  918759,
        919608,  919610,  919642,  919643,  919646,  919648,  919673,
        919674,  919733,  919734,  919735,  919736,  919740,  919742,
        919744,  919745,  919749,  919756,  919757,  919758,  919759,
        919760,  919761,  919762,  919763,  919764,  919771,  919772,
        919776,  919778,  919787,  919797,  919853,  919875,  920369,
        920370,  920371,  920372,  920378,  920379,  920380,  920381,
        920382,  920393,  920394,  920395,  920396,  920397,  920398,
        920399,  920400,  920401,  920402,  920409,  920410,  920411,
        920412,  920413,  920414,  920415,  920416,  920417,  920418,
        920419,  920420,  920421, 1075613, 1075614, 1075616, 1075619,
       1075623, 1075688, 1085572, 1085588, 1085589, 1085590, 1085592,
       1085593, 1085

In [25]:
import sys
sys.path.append("/home/papjuli/code/ETH/3DV_project/CityMagic3D")
from processing import BlocksExchange_xml_parser

In [26]:
caminfo_path = "/media/papjuli/Data/data/3DV_project/STPLS3D/Source_Images/Real_World/WMSC_CamInfoCC.xml"
intrinsic_matrix, poses_for_images, width, height = BlocksExchange_xml_parser.parse_xml(caminfo_path)

Photogroup Name: Photogroup 1
Intrinsic Matrix:
[[3.63257427e+03 0.00000000e+00 2.43685440e+03]
 [0.00000000e+00 3.63257427e+03 1.83817258e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Image Dimensions: 4864.0 3648.0
Photo ID: 0
Image Path: DJI_0001 (2).JPG
Pose Matrix:
[[ 4.54868829e-01 -8.90532417e-01 -6.80899896e-03  1.25889468e+02]
 [-6.39174697e-01 -3.21136529e-01 -6.98804005e-01  6.68328334e+01]
 [ 6.20121001e-01  3.22216299e-01 -7.15280785e-01 -1.40798392e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Photo ID: 1
Image Path: DJI_0001 (3).JPG
Pose Matrix:
[[-9.98907361e-01  3.11177434e-02  3.48679069e-02 -8.56967889e+01]
 [-4.21840098e-03  6.83008232e-01 -7.30398494e-01 -5.85148839e+01]
 [-4.65434204e-02 -7.29747519e-01 -6.82130683e-01 -1.59914333e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Photo ID: 2
Image Path: DJI_0002 (2).JPG
Pose Matrix:
[[ 4.57341666e-01 -8.89266825e-01 -6.56621723e-03  1.40271263e+02]
 [-6.368

In [27]:
intrinsic_matrix, poses_for_images, width, height

(array([[3.63257427e+03, 0.00000000e+00, 2.43685440e+03],
        [0.00000000e+00, 3.63257427e+03, 1.83817258e+03],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]]),
 {'DJI_0001 (2).JPG': array([[ 4.54868829e-01, -8.90532417e-01, -6.80899896e-03,
           1.25889468e+02],
         [-6.39174697e-01, -3.21136529e-01, -6.98804005e-01,
           6.68328334e+01],
         [ 6.20121001e-01,  3.22216299e-01, -7.15280785e-01,
          -1.40798392e+01],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           1.00000000e+00]]),
  'DJI_0001 (3).JPG': array([[-9.98907361e-01,  3.11177434e-02,  3.48679069e-02,
          -8.56967889e+01],
         [-4.21840098e-03,  6.83008232e-01, -7.30398494e-01,
          -5.85148839e+01],
         [-4.65434204e-02, -7.29747519e-01, -6.82130683e-01,
          -1.59914333e+01],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           1.00000000e+00]]),
  'DJI_0002 (2).JPG': array([[ 4.57341666e-01, -8.89266825e-01, -6.5

In [28]:
from instance_masks_from_images.scene import Camera

In [29]:
resolution = (4864, 3648)
camera = Camera(intrinsic_matrix, *resolution)

In [30]:
wmsc_pc_path = "/media/papjuli/Data/data/3DV_project/STPLS3D/point_clouds/RealWorldData/WMSC_points.ply"
pc_o3d = o3d.io.read_point_cloud(wmsc_pc_path)

In [31]:
# img_name = "DJI_0029 (3).JPG"
# img_name = "DJI_0014 (3).JPG"
img_name = "DJI_0341.JPG"
img_pose = poses_for_images[img_name]

In [32]:
camera_lines = o3d.geometry.LineSet.create_camera_visualization(
    view_width_px=resolution[0], view_height_px=resolution[1], 
    intrinsic=camera.intrinsic_matrix.copy(), 
    extrinsic=np.linalg.inv(img_pose),
    scale=20)

In [33]:
for mask in mask_indices_ls:
    np.asarray(pc_o3d.colors)[mask,:] = (np.random.random(3) + np.asarray(pc_o3d.colors)[mask,:]) / 2

In [34]:
o3d.visualization.draw_geometries([pc_o3d, camera_lines],
                                  zoom=0.34,
                                  front=[1, 0, 0.5],
                                  lookat=[0, 0, 0],
                                  up=[-0.5, 0, 1])